import { AgeState } from '../features/age/AgeState';
import { ConfirmMergeAccountState } from '../features/confirmMergeAccount/ConfirmMergeAccountState';
import { FastUnsubscribeState } from '../features/fastUnsubscribe/FastUnsubscribeState';
import { FavoritesState } from '../features/favorites/FavoritesState';
import { GoalCategoriesState } from '../features/goalCategories/GoalCategoriesState';
import { GoalDaysPerWeekState } from '../features/goalDaysPerWeek/GoalDaysPerWeekState';
import { GotoEmotionState } from '../features/gotoEmotion/GotoEmotionState';
import { HomeScreenState } from '../features/homeScreen/HomeScreenState';
import { HomeScreenTutorialState } from '../features/homeScreenTutorial/HomeScreenTutorialState';
import { IsaiahCourseState } from '../features/isaiahCourse/IsaiahCourseState';
import { LoginState } from '../features/login/LoginState';
import { ManageMembershipState } from '../features/manageMembership/ManageMembershipState';
import { MergeAccountState } from '../features/mergeAccount/MergeAccountState';
import { RequestNameState } from '../features/requestName/RequestNameState';
import { RequestNotificationTimeState } from '../features/requestNotificationTime/RequestNotificationTimeState';
import { RequestPhoneState } from '../features/requestPhone/RequestPhoneState';
import { SeriesDetailsState } from '../features/seriesDetails/SeriesDetailsState';
import { SeriesListState } from '../features/seriesList/SeriesListState';
import { SeriesPreviewState } from '../features/seriesPreview/SeriesPreviewState';
import { SettingsState } from '../features/settings/SettingsState';
import { ShareJourneyState } from '../features/shareJourney/ShareJourneyState';
import { SingleJourneyState } from '../features/singleJourney/SingleJourneyState';
import { TouchLinkState } from '../features/touchLink/TouchLinkState';
import { UpgradeState } from '../features/upgrade/UpgradeState';
import { VipChatRequestState } from '../features/vipChatRequest/VipChatRequestState';
import { WelcomeVideoState } from '../features/welcomeVideo/WelcomeVideoState';

export type FeatureAllStates = {
  requestName: RequestNameState;
  requestPhone: RequestPhoneState;
  requestNotificationTime: RequestNotificationTimeState;
  vipChatRequest: VipChatRequestState;
  goalDaysPerWeek: GoalDaysPerWeekState;
  favorites: FavoritesState;
  isaiahCourse: IsaiahCourseState;
  settings: SettingsState;
  touchLink: TouchLinkState;
  login: LoginState;
  fastUnsubscribe: FastUnsubscribeState;
  mergeAccount: MergeAccountState;
  confirmMergeAccount: ConfirmMergeAccountState;
  shareJourney: ShareJourneyState;
  seriesList: SeriesListState;
  seriesPreview: SeriesPreviewState;
  seriesDetails: SeriesDetailsState;
  upgrade: UpgradeState;
  manageMembership: ManageMembershipState;
  singleJourney: SingleJourneyState;
  homeScreen: HomeScreenState;
  gotoEmotion: GotoEmotionState;
  welcomeVideo: WelcomeVideoState;
  goalCategories: GoalCategoriesState;
  age: AgeState;
  homeScreenTutorial: HomeScreenTutorialState;
};
